IQ-125 Review flow for observation/survey
Sunbird-inQuiry/inquiry-api-service pull request #39
Opened 2023-10-06 11:05 UTC by Vivek-M-08

@krgauraw
Design doc approved by DC - https://project-sunbird.atlassian.net/l/cp/HDuR6Nmz
Story - https://project-sunbird.atlassian.net/browse/IQ-125

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java 11, scala-2.11, play-2.7.2
* Hardware versions: 2 CPU/ 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-11 06:41 UTC, krgauraw commented
@Vivek-M-08 Please write test cases to have coverage at least 80%
cc: @sajeshkayyath

2023-10-18 04:36 UTC, Vivek-M-08 commented
@krgauraw - To ensure the desired coverage, I have added required test-cases.

2023-10-27 06:45 UTC, krgauraw requested changes

2023-10-27 06:45 UTC, krgauraw commented on assessment-api/assessment-actors/src/main/scala/org/sunbird/managers/AssessmentManager.scala
> +				throw new ClientException("ERR_QUESTION_SET_ADD", s"Node with Identifier ${node.getIdentifier} is not a Question Set.")
Please change the error code

2023-10-27 06:45 UTC, krgauraw commented on assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/managers/AssessmentV5Manager.scala
> +        throw new ClientException("ERR_QUESTION_SET_ADD", s"Node with Identifier ${node.getIdentifier} is not a Question Set.")
please change the error code

2023-10-27 12:35 UTC, sajeshkayyath approved these changes

2023-10-27 12:35 UTC, merged