IQ-125 Modified Review flow for observation/survey
Sunbird-inQuiry/inquiry-api-service pull request #49
Opened 2024-01-25 09:12 UTC by Vivek-M-08

@krgauraw
Design doc approved by DC - https://project-sunbird.atlassian.net/l/cp/HDuR6Nmz
Story - https://project-sunbird.atlassian.net/browse/IQ-125

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java 11, scala-2.12, play-2.7.2
* Hardware versions: 2 CPU/ 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-01 10:00 UTC, krgauraw requested changes

2024-02-01 11:49 UTC, Vivek-M-08 commented on assessment-api/assessment-actors/src/main/scala/org/sunbird/v5/actors/QuestionSetActor.scala
> +        val responseMap = Map("identifier" -> node.getIdentifier.replace(".img", "").asInstanceOf[AnyRef])
Updated the design doc

2024-02-01 11:50 UTC, Vivek-M-08 commented on assessment-api/assessment-actors/src/main/scala/org/sunbird/actors/QuestionSetActor.scala
> +				val responseMap = Map("identifier" -> node.getIdentifier.replace(".img", "").asInstanceOf[AnyRef])
Updated the design doc

2024-02-02 08:52 UTC, krgauraw approved these changes

2024-02-02 08:53 UTC, merged